spring:
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/expensapp
    username: postgres
    password: admin

  # JPA Properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect

    # Hibernate ddl auto (create, create-drop, validate, update)
    # CREATE: Cada vez que se inicia la app, crea la tabla
    # CREATE-DROP: Cada vez que se inicia la app, crea la tabla y cuando se detiene la borra
    # VALIDATE: A revisar.
    # UPDATE: Crea la tabla si no existe, pero si existe la actualiza

    hibernate:
      ddl-auto: update
