logging:
  level:
    org:
      hibernate:
        type:
          description: 
            sql: 
              BasicBinder: TRACE
        SQL: DEBUG
spring:
  datasource:
    url: jdbc:postgresql://postgres:5433/expensapp?createDatabaseIfNotExist=true&serverTimezone=UTC
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
