logging:
  level:
    org:
      hibernate:
        type:
          description: 
            sql: 
              BasicBinder: TRACE
        SQL: DEBUG
spring:
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
